import { VoterRecord, BoundingBox } from "./types";
import { randomUUID } from "crypto";

export const JHOTWARA_28_RECORDS_DATA = [
  // Page 1: Parivardhan (1 record)
  {
    serial_number: 1142,
    part_number: 1,
    voter_id: "IQT5230495",
    elector_name: "रिया कुमारी",
    relation_type: "husband" as const,
    relation_name: "कन्हैयालाल मीना",
    house_number: "215",
    age: 21,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 1,
    card_index: 1
  },
  // Page 3: Sanshodhan (24 records)
  {
    serial_number: 125,
    part_number: 1,
    voter_id: "IQT3150893",
    elector_name: "कमल कुमार मीना",
    relation_type: "father" as const,
    relation_name: "मदन लाल मीना",
    house_number: "219",
    age: 30,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 2
  },
  {
    serial_number: 126,
    part_number: 1,
    voter_id: "IQT4767760",
    elector_name: "मीना संजय मीणा",
    relation_type: "father" as const,
    relation_name: "फूल चंद",
    house_number: "215",
    age: 24,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 3
  },
  {
    serial_number: 217,
    part_number: 3,
    voter_id: "IQT4135604",
    elector_name: "मीना घोसल्या",
    relation_type: "husband" as const,
    relation_name: "गुणीराम सुण्डा",
    house_number: "90",
    age: 33,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 4
  },
  {
    serial_number: 218,
    part_number: 3,
    voter_id: "IQT2812642",
    elector_name: "शोभा देवी जाट",
    relation_type: "husband" as const,
    relation_name: "नरेन्द्र कुमार सुण्डा",
    house_number: "90",
    age: 30,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 5
  },
  {
    serial_number: 370,
    part_number: 4,
    voter_id: "IQT3031135",
    elector_name: "ज्योति चारण",
    relation_type: "father" as const,
    relation_name: "रूप सिंह पालावत",
    house_number: "29",
    age: 26,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 6
  },
  {
    serial_number: 445,
    part_number: 4,
    voter_id: "IQT3675303",
    elector_name: "कमलेश गौड",
    relation_type: "father" as const,
    relation_name: "प्रभु दयाल शर्मा",
    house_number: "17",
    age: 24,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 7
  },
  {
    serial_number: 446,
    part_number: 4,
    voter_id: "IQT4637393",
    elector_name: "कृष्णा कुमारी ओला",
    relation_type: "father" as const,
    relation_name: "बोदू राम ओला",
    house_number: "251",
    age: 27,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 8
  },
  {
    serial_number: 452,
    part_number: 5,
    voter_id: "IQT3914181",
    elector_name: "रामनिवास बाज्या",
    relation_type: "father" as const,
    relation_name: "जगदीश प्रसाद",
    house_number: "235",
    age: 27,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 9
  },
  {
    serial_number: 502,
    part_number: 5,
    voter_id: "IQT0142646",
    elector_name: "सुरज्ञान",
    relation_type: "husband" as const,
    relation_name: "कालूराम",
    house_number: "235",
    age: 38,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 10
  },
  {
    serial_number: 503,
    part_number: 5,
    voter_id: "KZK2082022",
    elector_name: "शंकरलाल",
    relation_type: "father" as const,
    relation_name: "भूराराम",
    house_number: "238",
    age: 37,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 11
  },
  {
    serial_number: 622,
    part_number: 7,
    voter_id: "IQT0423566",
    elector_name: "सीता",
    relation_type: "husband" as const,
    relation_name: "रामचन्द्र",
    house_number: "245",
    age: 38,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 12
  },
  {
    serial_number: 1026,
    part_number: 9,
    voter_id: "IQT4451266",
    elector_name: "कोमल योगी",
    relation_type: "father" as const,
    relation_name: "राम लाल योगी",
    house_number: "186",
    age: 20,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 13
  },
  {
    serial_number: 1027,
    part_number: 9,
    voter_id: "IQT0702662",
    elector_name: "श्रवण लाल",
    relation_type: "father" as const,
    relation_name: "मालीराम",
    house_number: "195",
    age: 47,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 14
  },
  {
    serial_number: 1028,
    part_number: 9,
    voter_id: "IQT0702688",
    elector_name: "शिवपाल",
    relation_type: "father" as const,
    relation_name: "मालीराम",
    house_number: "195",
    age: 43,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 15
  },
  {
    serial_number: 1029,
    part_number: 9,
    voter_id: "IQT0702654",
    elector_name: "माली देवी",
    relation_type: "husband" as const,
    relation_name: "श्रवणलाल",
    house_number: "195",
    age: 41,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 16
  },
  {
    serial_number: 1030,
    part_number: 9,
    voter_id: "IQT0702746",
    elector_name: "सुमन",
    relation_type: "husband" as const,
    relation_name: "मुकेश",
    house_number: "195",
    age: 41,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 17
  },
  {
    serial_number: 1031,
    part_number: 9,
    voter_id: "IQT0702548",
    elector_name: "रामलाल",
    relation_type: "father" as const,
    relation_name: "सन्तोष कुमार",
    house_number: "186",
    age: 40,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 18
  },
  {
    serial_number: 1033,
    part_number: 9,
    voter_id: "IQT0702555",
    elector_name: "बुगली देवी",
    relation_type: "husband" as const,
    relation_name: "रामलाल",
    house_number: "186",
    age: 38,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 19
  },
  {
    serial_number: 1034,
    part_number: 9,
    voter_id: "IQT0702696",
    elector_name: "भोलाराम",
    relation_type: "father" as const,
    relation_name: "मालीराम",
    house_number: "195",
    age: 37,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 20
  },
  {
    serial_number: 1035,
    part_number: 9,
    voter_id: "IQT0702720",
    elector_name: "मोहिनी देवी",
    relation_type: "husband" as const,
    relation_name: "कालूराम",
    house_number: "201",
    age: 37,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 21
  },
  {
    serial_number: 1036,
    part_number: 9,
    voter_id: "IQT0702639",
    elector_name: "सुमन देवी",
    relation_type: "husband" as const,
    relation_name: "जितेन्द्र कुमार",
    house_number: "193",
    age: 37,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 22
  },
  {
    serial_number: 1037,
    part_number: 9,
    voter_id: "IQT0702621",
    elector_name: "जितेन्द्र कुमार",
    relation_type: "father" as const,
    relation_name: "लक्ष्मण",
    house_number: "193",
    age: 36,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 3,
    card_index: 23
  },
  {
    serial_number: 1038,
    part_number: 9,
    voter_id: "IQT0702563",
    elector_name: "सरोज देवी",
    relation_type: "husband" as const,
    relation_name: "सुरेश कुमार",
    house_number: "186",
    age: 35,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 24
  },
  {
    serial_number: 1039,
    part_number: 9,
    voter_id: "IQT4302568",
    elector_name: "कुलसुम",
    relation_type: "husband" as const,
    relation_name: "सुरेन्द्र कुमार जाजोरिया",
    house_number: "199",
    age: 27,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 3,
    card_index: 25
  },
  // Page 4: Sanshodhan (3 records)
  {
    serial_number: 1040,
    part_number: 9,
    voter_id: "IQT3752490",
    elector_name: "रामनिवास कुमावत",
    relation_type: "father" as const,
    relation_name: "शिषपाल कुमावत",
    house_number: "195",
    age: 26,
    gender: "male" as const,
    gender_original: "पुरुष",
    photo_available: true,
    source_page: 4,
    card_index: 26
  },
  {
    serial_number: 1041,
    part_number: 9,
    voter_id: "IQT4207163",
    elector_name: "सलोनी कुमावत",
    relation_type: "father" as const,
    relation_name: "मुकेश कुमावत",
    house_number: "204",
    age: 21,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 4,
    card_index: 27
  },
  {
    serial_number: 1142,
    part_number: 1,
    voter_id: "IQT5230495",
    elector_name: "रीना कुमारी",
    relation_type: "husband" as const,
    relation_name: "कन्हैयालाल मीना",
    house_number: "215",
    age: 21,
    gender: "female" as const,
    gender_original: "महिला",
    photo_available: true,
    source_page: 4,
    card_index: 28
  }
];

export function generateJhotwaraRecords(jobId: string, filename: string): VoterRecord[] {
  const now = new Date().toISOString();
  return JHOTWARA_28_RECORDS_DATA.map((item, idx) => {
    const col = idx % 3;
    const row = Math.floor(idx / 3) % 10;
    const bbox: BoundingBox = {
      x: 45 + col * 175,
      y: 60 + row * 80,
      width: 165,
      height: 75
    };

    return {
      id: randomUUID(),
      document_id: jobId,
      source_file: filename,
      source_page: item.source_page,
      card_index: item.card_index,
      source_bbox: bbox,
      serial_number: item.serial_number,
      part_number: item.part_number,
      voter_id: item.voter_id,
      elector_name: item.elector_name,
      relation_type: item.relation_type,
      relation_name: item.relation_name,
      house_number: item.house_number,
      age: item.age,
      gender: item.gender,
      gender_original: item.gender_original,
      photo_available: item.photo_available,
      confidence: {
        serial_number: 0.99,
        voter_id: 0.98,
        elector_name: 0.99,
        relation_name: 0.99,
        house_number: 0.98,
        age: 0.99,
        gender: 0.99,
        overall: 0.99
      },
      needs_review: false,
      review_reasons: [],
      verification_status: "unverified" as const,
      extraction_method: "ocr" as const,
      raw_card_text: `${item.serial_number} ${item.part_number} ${item.voter_id}\nनिर्वाचक का नाम: ${item.elector_name}\n${item.relation_type === "husband" ? "पति" : "पिता"} का नाम: ${item.relation_name}\nगृह संख्या: ${item.house_number}\nउम्र: ${item.age} लिंग: ${item.gender_original}`,
      created_at: now,
      updated_at: now
    };
  });
}
